import { Employee, SelectOptionProps } from '../types';

export const STATES: SelectOptionProps[] = [
  {
    value: 'AL',
    name: 'Alabama',
    abbreviation: 'AL',
  },
  {
    value: 'AK',
    name: 'Alaska',
    abbreviation: 'AK',
  },
  {
    value: 'AS',
    name: 'American Samoa',
    abbreviation: 'AS',
  },
  {
    value: 'AZ',
    name: 'Arizona',
    abbreviation: 'AZ',
  },
  {
    value: 'AR',
    name: 'Arkansas',
    abbreviation: 'AR',
  },
  {
    value: 'CA',
    name: 'California',
    abbreviation: 'CA',
  },
  {
    value: 'CO',
    name: 'Colorado',
    abbreviation: 'CO',
  },
  {
    value: 'CT',
    name: 'Connecticut',
    abbreviation: 'CT',
  },
  {
    value: 'DE',
    name: 'Delaware',
    abbreviation: 'DE',
  },
  {
    value: 'DC',
    name: 'District Of Columbia',
    abbreviation: 'DC',
  },
  {
    value: 'FM',
    name: 'Federated States Of Micronesia',
    abbreviation: 'FM',
  },
  {
    value: 'FL',
    name: 'Florida',
    abbreviation: 'FL',
  },
  {
    value: 'GA',
    name: 'Georgia',
    abbreviation: 'GA',
  },
  {
    value: 'GU',
    name: 'Guam',
    abbreviation: 'GU',
  },
  {
    value: 'HI',
    name: 'Hawaii',
    abbreviation: 'HI',
  },
  {
    value: 'ID',
    name: 'Idaho',
    abbreviation: 'ID',
  },
  {
    value: 'IL',
    name: 'Illinois',
    abbreviation: 'IL',
  },
  {
    value: 'IN',
    name: 'Indiana',
    abbreviation: 'IN',
  },
  {
    value: 'IA',
    name: 'Iowa',
    abbreviation: 'IA',
  },
  {
    value: 'KS',
    name: 'Kansas',
    abbreviation: 'KS',
  },
  {
    value: 'KY',
    name: 'Kentucky',
    abbreviation: 'KY',
  },
  {
    value: 'LA',
    name: 'Louisiana',
    abbreviation: 'LA',
  },
  {
    value: 'ME',
    name: 'Maine',
    abbreviation: 'ME',
  },
  {
    value: 'MH',
    name: 'Marshall Islands',
    abbreviation: 'MH',
  },
  {
    value: 'MD',
    name: 'Maryland',
    abbreviation: 'MD',
  },
  {
    value: 'MA',
    name: 'Massachusetts',
    abbreviation: 'MA',
  },
  {
    value: 'MI',
    name: 'Michigan',
    abbreviation: 'MI',
  },
  {
    value: 'MN',
    name: 'Minnesota',
    abbreviation: 'MN',
  },
  {
    value: 'MS',
    name: 'Mississippi',
    abbreviation: 'MS',
  },
  {
    value: 'MO',
    name: 'Missouri',
    abbreviation: 'MO',
  },
  {
    value: 'MT',
    name: 'Montana',
    abbreviation: 'MT',
  },
  {
    value: 'NE',
    name: 'Nebraska',
    abbreviation: 'NE',
  },
  {
    value: 'NV',
    name: 'Nevada',
    abbreviation: 'NV',
  },
  {
    value: 'NH',
    name: 'New Hampshire',
    abbreviation: 'NH',
  },
  {
    value: 'NJ',
    name: 'New Jersey',
    abbreviation: 'NJ',
  },
  {
    value: 'NM',
    name: 'New Mexico',
    abbreviation: 'NM',
  },
  {
    value: 'NY',
    name: 'New York',
    abbreviation: 'NY',
  },
  {
    value: 'NC',
    name: 'North Carolina',
    abbreviation: 'NC',
  },
  {
    value: 'ND',
    name: 'North Dakota',
    abbreviation: 'ND',
  },
  {
    value: 'MP',
    name: 'Northern Mariana Islands',
    abbreviation: 'MP',
  },
  {
    value: 'OH',
    name: 'Ohio',
    abbreviation: 'OH',
  },
  {
    value: 'OK',
    name: 'Oklahoma',
    abbreviation: 'OK',
  },
  {
    value: 'OR',
    name: 'Oregon',
    abbreviation: 'OR',
  },
  {
    value: 'PW',
    name: 'Palau',
    abbreviation: 'PW',
  },
  {
    value: 'PA',
    name: 'Pennsylvania',
    abbreviation: 'PA',
  },
  {
    value: 'PR',
    name: 'Puerto Rico',
    abbreviation: 'PR',
  },
  {
    value: 'RI',
    name: 'Rhode Island',
    abbreviation: 'RI',
  },
  {
    value: 'SC',
    name: 'South Carolina',
    abbreviation: 'SC',
  },
  {
    value: 'SD',
    name: 'South Dakota',
    abbreviation: 'SD',
  },
  {
    value: 'TN',
    name: 'Tennessee',
    abbreviation: 'TN',
  },
  {
    value: 'TX',
    name: 'Texas',
    abbreviation: 'TX',
  },
  {
    value: 'UT',
    name: 'Utah',
    abbreviation: 'UT',
  },
  {
    value: 'VT',
    name: 'Vermont',
    abbreviation: 'VT',
  },
  {
    value: 'VI',
    name: 'Virgin Islands',
    abbreviation: 'VI',
  },
  {
    value: 'VA',
    name: 'Virginia',
    abbreviation: 'VA',
  },
  {
    value: 'WA',
    name: 'Washington',
    abbreviation: 'WA',
  },
  {
    value: 'WV',
    name: 'West Virginia',
    abbreviation: 'WV',
  },
  {
    value: 'WI',
    name: 'Wisconsin',
    abbreviation: 'WI',
  },
  {
    value: 'WY',
    name: 'Wyoming',
    abbreviation: 'WY',
  },
];

export const DEPARTMENTS: SelectOptionProps[] = [
  { value: 'sales', name: 'Sales' },
  { value: 'marketing', name: 'Marketing' },
  { value: 'engineering', name: 'Engineering' },
  { value: 'human_resources', name: 'Human Resources' },
  { value: 'legal', name: 'Legal' },
];

export const EMPLOYEES: Employee[] = [
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
  {
    firstName: 'Johnnn',
    lastName: 'Doe',
    startDate: new Date('2020-01-01'),
    department: 'Engineering',
    dateOfBirth: new Date('1990-01-01'),
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: 12345,
  },
  {
    firstName: 'Janeee',
    lastName: 'Smith',
    startDate: new Date('2021-02-02'),
    department: 'Marketing',
    dateOfBirth: new Date('1992-02-02'),
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: 67890,
  },
];