import { Employee, SelectOptionProps } from '../types';

export const STATES: SelectOptionProps[] = [
  {
    value: 'AL',
    name: 'Alabama',
    abbreviation: 'AL',
  },
  {
    value: 'AK',
    name: 'Alaska',
    abbreviation: 'AK',
  },
  {
    value: 'AS',
    name: 'American Samoa',
    abbreviation: 'AS',
  },
  {
    value: 'AZ',
    name: 'Arizona',
    abbreviation: 'AZ',
  },
  {
    value: 'AR',
    name: 'Arkansas',
    abbreviation: 'AR',
  },
  {
    value: 'CA',
    name: 'California',
    abbreviation: 'CA',
  },
  {
    value: 'CO',
    name: 'Colorado',
    abbreviation: 'CO',
  },
  {
    value: 'CT',
    name: 'Connecticut',
    abbreviation: 'CT',
  },
  {
    value: 'DE',
    name: 'Delaware',
    abbreviation: 'DE',
  },
  {
    value: 'DC',
    name: 'District Of Columbia',
    abbreviation: 'DC',
  },
  {
    value: 'FM',
    name: 'Federated States Of Micronesia',
    abbreviation: 'FM',
  },
  {
    value: 'FL',
    name: 'Florida',
    abbreviation: 'FL',
  },
  {
    value: 'GA',
    name: 'Georgia',
    abbreviation: 'GA',
  },
  {
    value: 'GU',
    name: 'Guam',
    abbreviation: 'GU',
  },
  {
    value: 'HI',
    name: 'Hawaii',
    abbreviation: 'HI',
  },
  {
    value: 'ID',
    name: 'Idaho',
    abbreviation: 'ID',
  },
  {
    value: 'IL',
    name: 'Illinois',
    abbreviation: 'IL',
  },
  {
    value: 'IN',
    name: 'Indiana',
    abbreviation: 'IN',
  },
  {
    value: 'IA',
    name: 'Iowa',
    abbreviation: 'IA',
  },
  {
    value: 'KS',
    name: 'Kansas',
    abbreviation: 'KS',
  },
  {
    value: 'KY',
    name: 'Kentucky',
    abbreviation: 'KY',
  },
  {
    value: 'LA',
    name: 'Louisiana',
    abbreviation: 'LA',
  },
  {
    value: 'ME',
    name: 'Maine',
    abbreviation: 'ME',
  },
  {
    value: 'MH',
    name: 'Marshall Islands',
    abbreviation: 'MH',
  },
  {
    value: 'MD',
    name: 'Maryland',
    abbreviation: 'MD',
  },
  {
    value: 'MA',
    name: 'Massachusetts',
    abbreviation: 'MA',
  },
  {
    value: 'MI',
    name: 'Michigan',
    abbreviation: 'MI',
  },
  {
    value: 'MN',
    name: 'Minnesota',
    abbreviation: 'MN',
  },
  {
    value: 'MS',
    name: 'Mississippi',
    abbreviation: 'MS',
  },
  {
    value: 'MO',
    name: 'Missouri',
    abbreviation: 'MO',
  },
  {
    value: 'MT',
    name: 'Montana',
    abbreviation: 'MT',
  },
  {
    value: 'NE',
    name: 'Nebraska',
    abbreviation: 'NE',
  },
  {
    value: 'NV',
    name: 'Nevada',
    abbreviation: 'NV',
  },
  {
    value: 'NH',
    name: 'New Hampshire',
    abbreviation: 'NH',
  },
  {
    value: 'NJ',
    name: 'New Jersey',
    abbreviation: 'NJ',
  },
  {
    value: 'NM',
    name: 'New Mexico',
    abbreviation: 'NM',
  },
  {
    value: 'NY',
    name: 'New York',
    abbreviation: 'NY',
  },
  {
    value: 'NC',
    name: 'North Carolina',
    abbreviation: 'NC',
  },
  {
    value: 'ND',
    name: 'North Dakota',
    abbreviation: 'ND',
  },
  {
    value: 'MP',
    name: 'Northern Mariana Islands',
    abbreviation: 'MP',
  },
  {
    value: 'OH',
    name: 'Ohio',
    abbreviation: 'OH',
  },
  {
    value: 'OK',
    name: 'Oklahoma',
    abbreviation: 'OK',
  },
  {
    value: 'OR',
    name: 'Oregon',
    abbreviation: 'OR',
  },
  {
    value: 'PW',
    name: 'Palau',
    abbreviation: 'PW',
  },
  {
    value: 'PA',
    name: 'Pennsylvania',
    abbreviation: 'PA',
  },
  {
    value: 'PR',
    name: 'Puerto Rico',
    abbreviation: 'PR',
  },
  {
    value: 'RI',
    name: 'Rhode Island',
    abbreviation: 'RI',
  },
  {
    value: 'SC',
    name: 'South Carolina',
    abbreviation: 'SC',
  },
  {
    value: 'SD',
    name: 'South Dakota',
    abbreviation: 'SD',
  },
  {
    value: 'TN',
    name: 'Tennessee',
    abbreviation: 'TN',
  },
  {
    value: 'TX',
    name: 'Texas',
    abbreviation: 'TX',
  },
  {
    value: 'UT',
    name: 'Utah',
    abbreviation: 'UT',
  },
  {
    value: 'VT',
    name: 'Vermont',
    abbreviation: 'VT',
  },
  {
    value: 'VI',
    name: 'Virgin Islands',
    abbreviation: 'VI',
  },
  {
    value: 'VA',
    name: 'Virginia',
    abbreviation: 'VA',
  },
  {
    value: 'WA',
    name: 'Washington',
    abbreviation: 'WA',
  },
  {
    value: 'WV',
    name: 'West Virginia',
    abbreviation: 'WV',
  },
  {
    value: 'WI',
    name: 'Wisconsin',
    abbreviation: 'WI',
  },
  {
    value: 'WY',
    name: 'Wyoming',
    abbreviation: 'WY',
  },
];

export const DEPARTMENTS: SelectOptionProps[] = [
  { value: 'sales', name: 'Sales' },
  { value: 'marketing', name: 'Marketing' },
  { value: 'engineering', name: 'Engineering' },
  { value: 'human_resources', name: 'Human Resources' },
  { value: 'legal', name: 'Legal' },
];

export const DEFAULT_FORM_DATA = {
  firstName: '',
  lastName: '',
  dateOfBirth: '',
  startDate: '',
  department: DEPARTMENTS[0].value,
  street: '',
  city: '',
  state: STATES[0].value,
  zipCode: '',
};

export const EMPLOYEES: Employee[] = [
  {
    firstName: 'John',
    lastName: 'Doe',
    startDate: '2020-01-01',
    department: 'Engineering',
    dateOfBirth: '1990-01-01',
    street: '123 Main St',
    city: 'Anytown',
    state: 'CA',
    zipCode: '12345',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    startDate: '2021-02-02',
    department: 'Marketing',
    dateOfBirth: '1992-02-02',
    street: '456 Elm St',
    city: 'Othertown',
    state: 'NY',
    zipCode: '67890',
  },
  {
    firstName: 'Alice',
    lastName: 'Walker',
    startDate: '2019-03-15',
    department: 'Finance',
    dateOfBirth: '1988-07-22',
    street: '789 Pine St',
    city: 'Springfield',
    state: 'IL',
    zipCode: '62704',
  },
  {
    firstName: 'Bob',
    lastName: 'Anderson',
    startDate: '2018-06-11',
    department: 'Engineering',
    dateOfBirth: '1985-03-19',
    street: '321 Oak St',
    city: 'Lincoln',
    state: 'NE',
    zipCode: '68508',
  },
  {
    firstName: 'Carol',
    lastName: 'Mitchell',
    startDate: '2020-09-25',
    department: 'HR',
    dateOfBirth: '1991-12-01',
    street: '654 Maple St',
    city: 'Salem',
    state: 'OR',
    zipCode: '97301',
  },
  {
    firstName: 'David',
    lastName: 'Clark',
    startDate: '2022-01-04',
    department: 'Sales',
    dateOfBirth: '1993-10-10',
    street: '987 Cedar St',
    city: 'Boise',
    state: 'ID',
    zipCode: '83702',
  },
  {
    firstName: 'Emma',
    lastName: 'Scott',
    startDate: '2021-07-19',
    department: 'Marketing',
    dateOfBirth: '1989-05-25',
    street: '222 Walnut St',
    city: 'Denver',
    state: 'CO',
    zipCode: '80203',
  },
  {
    firstName: 'Frank',
    lastName: 'Reed',
    startDate: '2020-05-30',
    department: 'Finance',
    dateOfBirth: '1986-11-11',
    street: '111 Ash St',
    city: 'Madison',
    state: 'WI',
    zipCode: '53703',
  },
  {
    firstName: 'Grace',
    lastName: 'Bennett',
    startDate: '2019-11-07',
    department: 'HR',
    dateOfBirth: '1994-09-09',
    street: '333 Chestnut St',
    city: 'Albany',
    state: 'NY',
    zipCode: '12207',
  },
  {
    firstName: 'Henry',
    lastName: 'Morris',
    startDate: '2023-02-12',
    department: 'Engineering',
    dateOfBirth: '1995-01-20',
    street: '444 Birch St',
    city: 'Nashville',
    state: 'TN',
    zipCode: '37201',
  },
  {
    firstName: 'Isabella',
    lastName: 'Foster',
    startDate: '2022-10-28',
    department: 'Marketing',
    dateOfBirth: '1992-04-14',
    street: '555 Poplar St',
    city: 'Richmond',
    state: 'VA',
    zipCode: '23220',
  },
  {
    firstName: 'Jack',
    lastName: 'Perry',
    startDate: '2020-03-22',
    department: 'Sales',
    dateOfBirth: '1987-02-18',
    street: '666 Locust St',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43215',
  },
  {
    firstName: 'Karen',
    lastName: 'Cox',
    startDate: '2021-12-09',
    department: 'Finance',
    dateOfBirth: '1983-08-08',
    street: '777 Fir St',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30303',
  },
  {
    firstName: 'Liam',
    lastName: 'Gray',
    startDate: '2022-05-05',
    department: 'HR',
    dateOfBirth: '1996-06-06',
    street: '888 Redwood St',
    city: 'Austin',
    state: 'TX',
    zipCode: '73301',
  },
  {
    firstName: 'Mia',
    lastName: 'Hughes',
    startDate: '2018-08-16',
    department: 'Engineering',
    dateOfBirth: '1990-03-30',
    street: '999 Palm St',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85001',
  },
  {
    firstName: 'Noah',
    lastName: 'Rogers',
    startDate: '2019-01-14',
    department: 'Sales',
    dateOfBirth: '1984-12-12',
    street: '101 Hickory St',
    city: 'Salt Lake City',
    state: 'UT',
    zipCode: '84101',
  },
  {
    firstName: 'Olivia',
    lastName: 'Price',
    startDate: '2021-03-03',
    department: 'Marketing',
    dateOfBirth: '1991-09-17',
    street: '202 Beech St',
    city: 'Minneapolis',
    state: 'MN',
    zipCode: '55401',
  },
  {
    firstName: 'Paul',
    lastName: 'Jenkins',
    startDate: '2020-06-21',
    department: 'Engineering',
    dateOfBirth: '1982-07-07',
    street: '303 Sycamore St',
    city: 'Baltimore',
    state: 'MD',
    zipCode: '21201',
  },
  {
    firstName: 'Quinn',
    lastName: 'Mason',
    startDate: '2019-10-18',
    department: 'Finance',
    dateOfBirth: '1989-11-29',
    street: '404 Magnolia St',
    city: 'Raleigh',
    state: 'NC',
    zipCode: '27601',
  },
  {
    firstName: 'Rachel',
    lastName: 'Stone',
    startDate: '2023-01-01',
    department: 'HR',
    dateOfBirth: '1993-02-02',
    street: '505 Cottonwood St',
    city: 'Kansas City',
    state: 'MO',
    zipCode: '64106',
  },
  {
    firstName: 'Sam',
    lastName: 'Watson',
    startDate: '2018-04-14',
    department: 'Sales',
    dateOfBirth: '1986-10-15',
    street: '606 Dogwood St',
    city: 'Louisville',
    state: 'KY',
    zipCode: '40202',
  },
  {
    firstName: 'Tina',
    lastName: 'Long',
    startDate: '2022-08-08',
    department: 'Marketing',
    dateOfBirth: '1997-01-13',
    street: '707 Willow St',
    city: 'Milwaukee',
    state: 'WI',
    zipCode: '53202',
  },
  {
    firstName: 'Umar',
    lastName: 'Young',
    startDate: '2020-11-11',
    department: 'Engineering',
    dateOfBirth: '1990-06-23',
    street: '808 Larch St',
    city: 'Cincinnati',
    state: 'OH',
    zipCode: '45202',
  },
  {
    firstName: 'Vera',
    lastName: 'Barnes',
    startDate: '2019-07-30',
    department: 'HR',
    dateOfBirth: '1988-05-05',
    street: '909 Alder St',
    city: 'Buffalo',
    state: 'NY',
    zipCode: '14201',
  },
];